### ISSUE TITLE
Message & options additional control

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/web#48]
According to this doc : 
https://www.twilio.com/docs/glossary/what-sms-character-limit

> Messages containing any UCS-2 characters are limited to 67 characters and will be concatenated into 67 character message segments, even if the messages contain less than 160 characters.

It may be worth to prevent the input of UCS-2 chars as this can end up in a truncation of the whole message.

**Comment by ninsuo** [comment]
Done in #65
